name: Deploy to google play
on:
  push:
    branches: [master]


jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache : 'gradle'
      - name: grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run unit test
        run: ./gradlew clean testDebug


  distribute:
    name: distribue bundle to google play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: version bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: assemble release bundle
        run: ./gradlew assembleReleaseBundle

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{secrets.ANDROID_KEYSTORE}}
          keyStorePassword: ${{secrets.KEYSTORE_PASSWORD}}
          alias: ${{secrets.ANDROID_DEVS_ALIAS}}
          keyPassword: ${{secrets.ANDROID_DEV_ALIAS_PASSWORD}}

      - name: Setup Athorization with Google play store
        run: echo '${{secrets.PLAY_AUTH_JSON}}' > service_account.json

      - name: deploy bundle to google play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.vs.vibeplayer
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: 'completed'
          whatsNewDirectory: whatsNew/